version: '3.8'

services:
  wordpress:
    container_name: wordpress
    image: jdrdock/wordpress-astra:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - /opt/webapps/wordpress/content:/var/www/html/wp-content
    networks:
      - prod-net

  db:
    image: mysql:5.7
    restart: always
    container_name: prod_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_USER: wordpress
      MYSQL_DATABASE: wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - prod-net

  nginx:
    build:
      context: /opt/webapps/nginx
      dockerfile: nginx-custom.Dockerfile
    image: nginx:alpine
    restart: always
    command: /bin/sh -c "/etc/nginx/nginx-start.sh"
    ports:
      - "192.168.1.171:80:80"
      - "192.168.1.171:443:443"
    volumes:
      - /opt/webapps/nginx/nginx.prod.conf:/etc/nginx/nginx.conf
      - /etc/ssl/cloudflare:/etc/ssl/cloudflare:ro                                                                                                
    networks:
      - prod-net
    environment:
      - NGINX_ENV=dev

volumes:
  db_data:

networks:
  prod-net:
    external: true
