version: '3.8'

services:
  wordpress:
    container_name: dev_wordpress
    image: jdrdock/wordpress-astra:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
    networks:
      - dev-net
    volumes:
      - /opt/webapps/wordpress/content:/var/www/html/wp-content
    extra_hosts:
      - "dev.nimbledev.io:127.0.0.1"

  db:
    container_name: dev_db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - dev-net

  nginx:
    container_name: dev_nginx
    build:
      context: /opt/webapps/nginx
      dockerfile: nginx-custom.Dockerfile
    image: nginx:alpine
    restart: always
    command: /bin/sh -c "/etc/nginx/nginx-start.sh"
    ports:
      - '${HOST_LAN_IP}:80:80'
      - '${HOST_LAN_IP}:443:443'
    volumes:
      - /opt/webapps/nginx/nginx.dev.conf:/etc/nginx/nginx.conf
      - /etc/ssl/cloudflare:/etc/ssl/cloudflare:ro
    networks:
      - dev-net
    environment:
      - NGINX_ENV=dev
      - HOST_LAN_IP=${HOST_LAN_IP}

networks:
  dev-net:
    name: dev-net

volumes:
  db_data:

